import {changeStyleBody} from '../../components/Utils';

import styleRecetas from './Recetas.module.css';

export default function Recetas(){
    changeStyleBody('fondorosa','fondoturquesa');
    return(
        <div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
    </div>
        );
}