import {changeStyleBody} from '../../components/Utils';

import styleProducto from './Producto.module.css';

export default function Producto(){
    changeStyleBody('fondoturquesa','fondorosa');  
    return(
        <div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
    </div>
        );
}