import {changeStyleBody} from '../../components/Utils';
import styleReceta from './Receta.module.css';
export default function Receta(){
    changeStyleBody('fondorosa','fondoturquesa');
    return(
        <div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
    </div>
        );
}