import {changeStyleBody} from '../components/Utils';
export default function Contacto(){
    changeStyleBody('fondoazuloscuro','fondorosa');
    return(
        <div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
            <div>Contacto</div>
        </div>
    );
}