import {changeStyleBody} from '../components/Utils';

export default function Inicio() {
  changeStyleBody('fondoturquesa','fondorosa');  
  return (
    <div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    <div>inicio</div>
    </div>
  );
}
