import {changeStyleBody} from '../components/Utils';
export default function LaHoguera(){
    changeStyleBody('fondoamarillo','fondomorado');
    return(
        <div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
        <div>LaHoguera</div>
    </div>
    );
}