import {changeStyleBody} from '../components/Utils';
export default function LaTribu(){
    changeStyleBody('fondoazuloscuro','fondoturquesa');
    return(
        <div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
        <div>LaTribu</div>
    </div>
        );
}