import {changeStyleBody} from '../components/Utils';
export default function Productos(){
    changeStyleBody('fondoturquesa','fondorosa');  
    return(
        <div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
        <div>Productos</div>
    </div>
        );
}