import {changeStyleBody} from '../components/Utils';
export default function Producto(){
    changeStyleBody('fondoturquesa','fondorosa');  
    return(
        <div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
        <div>Producto</div>
    </div>
        );
}