import {changeStyleBody} from '../components/Utils';
export default function Recetas(){
    changeStyleBody('fondorosa','fondoturquesa');
    return(
        <div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
        <div>Recetas</div>
    </div>
        );
}