import {changeStyleBody} from '../components/Utils';
export default function Receta(){
    changeStyleBody('fondorosa','fondoturquesa');
    return(
        <div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
        <div>Receta</div>
    </div>
        );
}